pub mod config;
pub mod input;
pub mod key;
use crate::config::*;
use crate::input::*;
use crate::key::*;
use std::fs;
use std::fs::File;
use std::io::Read;
use std::mem;
use std::path::{Path, PathBuf};
use std::thread;
